language: cpp

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - intltool
      - autoconf
      - autopoint
      - libxml2-dev
      - pciutils-dev
      - libgtk2.0-dev

env:
  matrix:
    -
    - CFLAGS='CFLAGS=-O0 -g'
    - CFLAGS='CFLAGS=-O2'

compiler:
  - clang
  - gcc

script:
  - ./autogen.sh
  - ./configure "${CFLAGS}"
  - make -j4

